global using System;
global using Terraria;
global using Terraria.ID;
global using Terraria.ModLoader;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Luminance.Common.Utilities;
global using static System.MathF;
global using static Luminance.Common.Utilities.Utilities;
global using static Microsoft.Xna.Framework.MathHelper;
global using static NoxusBoss.Assets.GennedAssets.Textures.GreyscaleTextures;
global using static NoxusBoss.Assets.GennedAssets.Textures.Noise;
global using static NoxusBoss.Core.Utilities.Utilities;
using Luminance.Core.ModCalls;
using NoxusBoss.Core.Netcode;
using Terraria.ModLoader;